### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by alexisabril** [bitovi/funcunit.com#1]
_Issue by **[alexisabril](http://github.com/alexisabril)** from 2013-10-10T19:17:57Z_
_Originally opened as https://github.com/bitovi/funcunit/issues/52_

----
_Issue by **[moschel](https://github.com/moschel)** from Tuesday Sep 03, 2013 at 15:07 GMT_
_Originally opened as https://github.com/bitovi/funcunit.js/issues/5_

----

Homepage needs a brief feature list (why should I use this?) similar to canjs.com

**Comment by marshallswain** [comment]
@alexisabril If you can write a list up I can look at getting it on the site.  The site is loading from the gh-pages branch of the funcunit repository onto the DocumentJS CI server, now, so we can remove this repo after these issues get cleaned up.

**Comment by marshallswain** [comment]
Since this is the last remaining issue in this repo, I'm going to reopen the original issue and close this one.
