### ISSUE TITLE
Bitovi menu incorrect links

### ISSUE THREAD

**Issue by tomgreever** [bitovi/funcunit.com#10]
This menu is using the old Bitovi.com nav and links. Should be updated to change Consulting to Development and add Design, change People to About: 
![screen shot 2014-12-10 at 12 40 52 pm](https://cloud.githubusercontent.com/assets/326843/5381743/de9bb4ce-8069-11e4-9559-a40b53ac3618.png)

**Comment by marshallswain** [comment]
@tomgreever would you mind checking that this PR is what we're after?  I used the menu from the StealJS website since it's the newest one we have right now.

**Comment by marshallswain** [comment]
BTW, @daffl and I have moved the FuncUnit.com site to the gh-pages branch of the funcunit repo.  It's building to the DocumentJS CI server, now.

**Comment by marshallswain** [comment]
Menu updated.
![correct-menu-order](https://cloud.githubusercontent.com/assets/128857/7621172/f48ea020-f981-11e4-8184-7456c10fc48c.jpg)
