### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by alexisabril** [bitovi/funcunit.com#2]
_Issue by **[alexisabril](http://github.com/alexisabril)** from 2013-10-10T19:17:58Z_
_Originally opened as https://github.com/bitovi/funcunit/issues/54_

----
_Issue by **[daffl](https://github.com/daffl)** from Tuesday Sep 03, 2013 at 16:21 GMT_
_Originally opened as https://github.com/bitovi/funcunit.js/issues/9_

----

I really like the FuncUnit page design but I think that the flat style from the front page can also be brought over to the API and guides by removing some of the borders and just using background colors. Attached an example screenshot:

![screen shot 2013-09-03 at 10 15 16 am](https://f.cloud.github.com/assets/338316/1074184/cec1aae4-14b4-11e3-98de-d0b34a83d094.png)

What do you think @tomgreever?

**Comment by marshallswain** [comment]
@alexisabril It seems like the design has probably been updated since this issue was made.  Just to be sure, do you feel like this is still relevant?

**Comment by marshallswain** [comment]
I updated the design to match the new DocumentJS style today:

### Before:
![funcunit-before](https://cloud.githubusercontent.com/assets/128857/7621193/15b20328-f982-11e4-9b6f-20ad88b5c6bb.jpg)

### After:
![funcunit-after](https://cloud.githubusercontent.com/assets/128857/7621201/23562cd4-f982-11e4-977a-1193c2655d46.jpg)
